### ISSUE TITLE
Tor immediately shuts down

### ISSUE THREAD

**Issue by craigraw** [05nelsonm/kmp-tor#285] opened 2023-03-15 09:47 UTC
I've started writing a demo JavaFX app in Java to test out kmp-tor: https://github.com/craigraw/kmp-tor-java

I've run into a problem to which the answer is not readily apparent - Tor shuts down/is destroyed immediately on startup:
```
Lifecycle(class=RealTorManager@1605316700, event=onCreate)
State(torState=Tor: Starting, networkState=Network: Disabled)
Action.Start
I/Starting Tor with the following settings:
----------------------------------------------------------------
ControlPort 9051
SocksPort 9050
CacheDirectory /var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/cache
ControlPortWriteToFile /var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/control.txt
CookieAuthFile /var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/control_auth_cookie
CookieAuthentication 1
DataDirectory /var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/data
DisableNetwork 1
DormantCanceledByStartup 1
GeoIPFile /var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/geoip
GeoIPv6File /var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/geoip6
RunAsDaemon 0
SyslogIdentityTag TorManager
__OwningControllerProcess 8796
----------------------------------------------------------------
D/Reading Process.inputStream
D/Reading Process.errorStream
D/Tor Process destroyed
D/Stopped reading Process.inputStream
D/Stopped reading Process.errorStream
State(torState=Tor: Off, networkState=Network: Disabled)
E/io.matthewnelson.kmp.tor.manager.common.exceptions.TorManagerException: Failed to read control.txt
```

I'd also appreciate any insight on:
1. Whether my Java syntax of interacting with the Kotlin libraries is correct (my Kotlin knowledge is limited)
2. The recommended approach to create a Tor-based socket. I have been using https://github.com/JesusMcCloud/netlayer/blob/master/tor/src/main/kotlin/org/berndpruenster/netlayer/tor/TorSockets.kt, which in turn relies on `com.runjva.sourceforge.jsocks.protocol.SocksSocket`.

**Comment by 05nelsonm** [comment] 2023-03-15 10:24
> ```
> E/io.matthewnelson.kmp.tor.manager.common.exceptions.TorManagerException: Failed to read control.txt
> ```

Not 100% certain why it is failing immediately; there is a 10s limit set to wait for Tor to create the file [REF](https://github.com/05nelsonm/kmp-tor/blob/c44dc30b64ea2e8d94bf38b47ef48c1bb1c9e36a/library/manager/kmp-tor-manager/src/jvmAndroidMain/kotlin/io/matthewnelson/kmp/tor/manager/KmpTorLoader.kt#L265)

> 1. Whether my Java syntax of interacting with the Kotlin libraries is correct (my Kotlin knowledge is limited)

Kotlin compiles it down to java byte code, so should not be an issue at all. There are some things that are a little wonky with IDEs not liking some inheritance structures, but Java interop is great. Best bet is to follow the `:samples:java:javafx` sample provided.

> 2.  The recommended approach to create a Tor-based socket. I have been using
Not necessary anymore. `kmp-tor` is all event based whereby things are dispatched to whatever listeners you have attached to `TorManager`. This is to create a buffered medium between Tor, and your application's state.

Once Tor is done bootstrapping, an `AddressInfo` object is dispatched to your listeners such that you are able to instantiate whatever http client you want to use, however you see fit. See [HERE](https://github.com/05nelsonm/kmp-tor/blob/c44dc30b64ea2e8d94bf38b47ef48c1bb1c9e36a/samples/java/javafx/src/main/java/io/matthewnelson/kmp/tor/sample/java/javafx/App.java#L315).

I was adamant about limiting dependencies to only what was absolutely necessary. You can utilize just a straight up `java.net.Socket` by passing it the resulting `ProxyAddress` (retrieved from the `AddressInfo`).

```kotlin
private fun createSocksSocket(proxy: ProxyAddress): Socket {
    return Socket(
        Proxy(
            Proxy.Type.Socks,
            InetSocketAddress(proxy.address.value, proxy.port.value)
        )
    )
}
```

In the event you modify the Socks, Http, Trans, Dns, etc ports or UnixSocket addresses, once Tor has finished reacting to what it received over the control port, another `AddressInfo` object will be dispatched with the changes.

**Comment by 05nelsonm** [comment] 2023-03-15 10:33
Oh! try applying the kotlin gradle plugin

**Comment by 05nelsonm** [comment] 2023-03-15 10:56
> Oh! try applying the kotlin gradle plugin
> 
> ```groovy
> plugins {
>     id 'org.jetbrains.kotlin.jvm' version '1.8.10'
> }
> ```

Tried your sample with the `kotlin jvm` plugin. Works for me on `linux x64` and `macOS x64`.

**Comment by 05nelsonm** [comment] 2023-03-15 11:41
Also, you're instantiating new instances of `TorManager` every time the button is clicked. The instance should be static, and the button click should just call `torManager.startQuietly()`.

**Comment by craigraw** [comment] 2023-03-15 13:02
Thanks for the PR, and the other answers - I completely missed the Java example, which is very useful! 

Unfortunately, no change on this particular issue. I did a test on macOS x64 and it runs fine, so it appears to be related to the macOS arm64 binaries. After upgrading JavaFX to v18 on the sample app, and making a few changes to ensure that the arm64 binaries are installed, I managed to reproduce the issue on the Java sample app too.

Executing the extracted Tor directly results in
```shell
/var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/kmptor-j/work/.kmptor/tor
[1]    10978 killed     /var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/kmptor-j/work/.kmptor/tor
```

I'll keep digging to see if I can find any root cause.

**Comment by craigraw** [comment] 2023-03-15 13:16
I believe this might be related to a MacOS signature issue. When I sign the tor binary with my developer certificate, it executes successfully and Tor starts as normal, instead of being immediately killed. I haven't yet managed to get the Java app to work however.

**Comment by craigraw** [comment] 2023-03-15 14:04
Confirmed - I've managed to get the Java app to start by signing the `tor` and`libevent-2.1.7.dylib` arm64 binaries. They appear to be unsigned:
```
❯ spctl --assess --type install --context context:primary-signature -v "/var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/.kmptor/libevent-2.1.7.dylib"
/var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/.kmptor/libevent-2.1.7.dylib: rejected
source=no usable signature
❯ spctl --assess --type install --context context:primary-signature -v "/var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/.kmptor/tor"
/var/folders/7y/cvqm9r6n0cgddhm921cm1zwc0000gn/T/.kmp-tor-java/work/.kmptor/tor: rejected
source=no usable signature
```

**Comment by 05nelsonm** [comment] 2023-03-15 14:39
Just checked the `macosx64` binaries and they are unsigned as well. :thinking: 

Looking into this.

**Comment by 05nelsonm** [comment] 2023-03-15 15:17
So even the expert bundles that the tor project publishes [HERE](https://dist.torproject.org/torbrowser/12.5a3/) are unsigned.

```shell
wget https://dist.torproject.org/torbrowser/12.5a3/tor-expert-bundle-12.5a3-macos-x86_64.tar.gz
wget https://dist.torproject.org/torbrowser/12.5a3/tor-expert-bundle-12.5a3-macos-aarch64.tar.gz
tar -xzf tor-expert-bundle-12.5a3-macos-x86_64.tar.gz
cd tor
spctl --assess --type install --context context:primary-signature -v tor
spctl --assess --type install --context context:primary-signature -v libevent-2.17.dylib
cd ..
rm -rf tor
rm -rf data
tar -xzf tor-expert-bundle-12.5a3-macos-aarch64.tar.gz
cd tor
spctl --assess --type install --context context:primary-signature -v tor
spctl --assess --type install --context context:primary-signature -v libevent-2.17.dylib
```

Unfortunate :cry: 

Got a few q's that I hope you may be able to answer:
 - How might I go about signing the binaries so that `spctl` returns correctly?
     - Is it just `PGP` signatures, or some apple thing (sorry not an apple user)?
 - Will signing them alter the byte code such that they are no longer reproducible?

**Comment by craigraw** [comment] 2023-03-15 15:47
To ad hoc sign binaries you can do
```
codesign --force --deep -s - tor
codesign --force --deep -s - libevent-2.1.7.dylib
```
This does however change the files.

However, it's confusing: I am able to run the `tor` contained in `tor-expert-bundle-12.5a3-macos-aarch64.tar.gz`. `spctl` returns the same
```
spctl --assess -v tor
tor: rejected
source=no usable signature
```

Back on `kmptor`, I have found the relevant error when the process is killed in the macOS Console:
```
AMFI: hook..execve() killing pid 12760: Attempt to execute completely unsigned code (must be at least ad-hoc signed).
```

This article provides more information: https://eclecticlight.co/2021/01/26/when-you-dont-have-permission-to-run-an-app-on-an-m1-mac/

Still looking into this.

**Comment by 05nelsonm** [comment] 2023-03-15 16:44
> However, it's confusing: I am able to run the tor contained in tor-expert-bundle-12.5a3-macos-aarch64.tar.gz. spctl returns the same

Does the system check for signatures every single time they are executed on? Only thing I can think of is that you signed the files previously and the system didn't check after you replaced them with those from the expert bundle.

Trying to figure out how I might overcome this. Was banking on these binaries being reproducibly built for security purposes, verifiable by anyone by simply running the build script. Binaries from TorBrowser for macOS are signed, but they're combined `x86_64` + `aarch64` (they run on both architectures). So cannot yeet them from there.

Going to publish a `-SNAPSHOT` version of the expert bundle binaries repackaged, if you could try running those on `aarch64`?

**Comment by craigraw** [comment] 2023-03-15 17:06
> Does the system check for signatures every single time they are executed on? 

Yes, every time. It's pretty mental. I can reproduce all of this reliably (so I don't think it's due to some previous action I took), but I'm completely stumped as to why the expert bundle `tor` works. Perhaps macOS has an exception for it?

> Going to publish a `-SNAPSHOT` version of the expert bundle binaries repackaged, if you could try running those on `aarch64`?

Yes sure

**Comment by 05nelsonm** [comment] 2023-03-15 17:52
Alright, I published a `-SNAPSHOT` of [kmp-tor-binary branch issue/66-repackage-expert-bundle](https://github.com/05nelsonm/kmp-tor-binary/tree/issue/66-repackage-expert-bundle) which is just a repacking of all the expert bundles (after gpg verifying each, will move this into a script if we're successful).

If you could add to your build.gradle file the following:
 - maven repository `https://s01.oss.sonatype.org/content/repositories/snapshots/`
 - dependency `io.matthewnelson.kotlin-components:kmp-tor-binary-macosarm64:4.7.13-2-SNAPSHOT`

and give it a try.

**Comment by craigraw** [comment] 2023-03-15 18:31
Unfortunately that didn't work :( Same error as before, `Attempt to execute completely unsigned code`

It gets stranger though: I have verified that the `tor` from the expert bundle is exactly the same as the `tor` that is unpacked (with `shasum -a 256 tor`). So it appears to be something external to the file that is the culprit here. I had previously thought this to be something related to `xattr`, but neither of the files report anything from `xattr tor`. It does however look like signatures can get stripped with some kinds of compression: https://eclecticlight.co/2019/11/12/preparing-for-new-security-rules-how-signatures-can-get-stripped/. 

That said, it gets even stranger - copying `tor` and `libevent` extracted from `kmptor` into the extracted expert bundle also results in working Tor. So there is something else about the expert bundle that is the key. I'll keep looking tomorrow.

**Comment by 05nelsonm** [comment] 2023-03-15 20:12
Think there is some sort of linking behavior that is being preserved by the tar archive? On Linux for the process environment it is setting [LD_LIBRARY_PATH](https://github.com/05nelsonm/kmp-tor/blob/c44dc30b64ea2e8d94bf38b47ef48c1bb1c9e36a/library/kmp-tor/src/jvmMain/kotlin/io/matthewnelson/kmp/tor/KmpTorLoaderJvm.kt#L91)

Could you this repo and try running the sample, and if error try modifying that line to also be

```kotlin
if (installer.isLinux || installer.isMacos) {
```
?

**Comment by craigraw** [comment] 2023-03-16 06:43
Ok, I think I have found the issue. For some reason, macOS prevents calling an unsigned binary with a path, but allows it to be called without a path from the directory the binary is located in. This is what I was doing previously by accident - calling the expert bundle `tor` without a path specified, but specifying the full path to the extracted `tor` used by kmptor.

I have verified that this works:
```java
ProcessBuilder pb = new ProcessBuilder("tor");
pb.directory(new File(System.getProperty("user.home") + "/tor"));
p = pb.start();
```

while this does not:
```java
ProcessBuilder pb = new ProcessBuilder(System.getProperty("user.home") + "/tor/tor");
p = pb.start();
```

**Comment by 05nelsonm** [comment] 2023-03-16 10:40
I think that's running the tor instance you have installed on your machine, not the binaries that we are extracting. I tried modifying the loader to use `tor` instead of the absolute path to the extracted tor file, and debug info indicated that it was running an older version of tor (the version I have on my linux laptop). Running the same code on macOS x86_64 vm resulted in a file not found error (b/c tor is not installed as a package on there).

**Comment by 05nelsonm** [comment] 2023-03-16 11:11
Going to yeet the binaries from TorBrowser (b/c they're signed) and publish another `-SNAPSHOT` if you could test them out for on your M1/2.

**Comment by craigraw** [comment] 2023-03-16 11:52
> I think that's running the tor package you have installed on your machine

You're right - seems obvious in retrospect!

> Going to codesign macos binaries

Great. Note it [doesn't look like](https://apple.stackexchange.com/questions/288291/what-are-the-restrictions-of-ad-hoc-code-signing) the adhoc signing I mentioned above helps much. A developer certificate is needed for `codesign` to create distributable binaries afaik.

**Comment by craigraw** [comment] 2023-03-16 12:07
It worked! It looks like the adhoc signing is enough, at least for my machine.

That said, it's probably better to have a developer cert signed binary, since `spctl` still rejects it, so I'm not feeling that confident yet.

**Comment by 05nelsonm** [comment] 2023-03-16 12:17
> That said, it's probably better to have a developer cert signed binary

Definitely. Will ask devs if they plan to codesign the expert package binaries or not in order to figure out next steps (build program that extracts tor from TorBrowser, or uses the expert package which I much prefer).

Can publish a new release (`4.7.13-2`) using developer cert signed binaries from TorBrowser macos in the mean time if that works for you?

**Comment by 05nelsonm** [comment] 2023-03-16 16:51
Release [4.7.13-2-1.4.0][release] has been published which resolves things for the time being.

Further work on the binary build/verification process to resolve the underlying issues found in this ticket can be followed via [kmp-tor-binary #66][kmp-tor-binary-issue-66], which will be completed before the next tor version bump from `0.4.7.13`.

Closing this ticket, and picking things up in [kmp-tor-binary-#66][kmp-tor-binary-issue-66]

Thanks for helping figure this thing out @craigraw !

[release]: https://github.com/05nelsonm/kmp-tor/releases/tag/4.7.13-2-1.4.0
[kmp-tor-binary-issue-66]: https://github.com/05nelsonm/kmp-tor-binary/issues/66

**Closed by 05nelsonm** 2023-03-16 16:51 UTC
